import { Movie, Theater, Review } from '@/types'

const MOCK_MOVIES: Movie[] = [
  {
    id: '1',
    title: '다이버전트: 다크 에디션',
    overview: '어둠의 세계에서 빛과 어둠이 맞붙는 마지막 전쟁이 시작된다. 두 영웅의 운명이 교차하는 순간, 세상의 균형이 무너진다.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8b8R8l889jeHVMPag0HPwcBnSpR.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/8b8R8l889jeHVMPag0HPwcBnSpR.jpg',
    rating: 8.7,
    genre: '액션',
    releaseDate: new Date('2025-04-23'),
    runningTime: 148,
    director: '조너선 글래더슨',
    cast: ['앤 해서웨이', '제시카 차스테인', '매슈 맥코너키'],
    openDate: new Date('2025-04-23'),
    closeDate: null,
    status: 'now_playing',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    title: '미션 임파서블 8',
    overview: '이본 헌트와 IMF 팀이 세계를 구하기 위한 최후의 미션에 나선다. 예상을 초월한 액션과 스릴이 기다린다.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8b8R8l889jeHVMPag0HPwcBnSpR.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/8b8R8l889jeHVMPag0HPwcBnSpR.jpg',
    rating: 8.5,
    genre: '액션',
    releaseDate: new Date('2025-05-23'),
    runningTime: 165,
    director: '크리스토퍼 맥쿼리',
    cast: ['톰 크루즈', '하이리 스타인베르크', '반 킬리프'],
    openDate: new Date('2025-05-23'),
    closeDate: null,
    status: 'upcoming',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    title: '인사이드 아웃 3',
    overview: '라이리의 새로운 성장 과정에서 다양한 감정이 복잡하게 얽힌다. 분노, 슬픔, 두려움이 새로운 감정으로 합류하다.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8b8R8l889jeHVMPag0HPwcBnSpR.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/8b8R8l889jeHVMPag0HPwcBnSpR.jpg',
    rating: 8.3,
    genre: '애니메이션',
    releaseDate: new Date('2025-06-14'),
    runningTime: 112,
    director: '켁시 마르셜',
    cast: ['애미 포터머', '필리스 스미', '마이트 라오'],
    openDate: new Date('2025-06-14'),
    closeDate: null,
    status: 'upcoming',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    title: '오스: 레퀴엠',
    overview: '오스 세계의 비밀이 하나둘 드러나기 시작한다. 예상치 못한 반전과 함께 새로운 적의 등장으로 위기가 깊어진다.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8b8R8l889jeHVMPag0HPwcBnSpR.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/8b8R8l889jeHVMPag0HPwcBnSpR.jpg',
    rating: 7.9,
    genre: 'SF',
    releaseDate: new Date('2025-03-14'),
    runningTime: 134,
    director: '대프드 프랭코',
    cast: ['토머스 맥너', '앤드루 가필드', '제시카 알바'],
    openDate: new Date('2025-03-14'),
    closeDate: new Date('2025-05-14'),
    status: 'completed',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    title: '컨저링: 더 데빌 MADE ME DO IT',
    overview: '워렌 부부가 가장 충격적인 초자연적 사건에 휘말린다. 사탄의 간섭으로 인한 첫 번째 살인 방어 주장의 실제 사건.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8b8R8l889jeHVMPag0HPwcBnSpR.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/8b8R8l889jeHVMPag0HPwcBnSpR.jpg',
    rating: 7.6,
    genre: '공포',
    releaseDate: new Date('2025-05-17'),
    runningTime: 112,
    director: '대비스 스콧',
    cast: ['버니 피츠제럴드', '패트릭 윌슨', '버니 피츠제럴드'],
    openDate: new Date('2025-05-17'),
    closeDate: null,
    status: 'upcoming',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    title: '기생충',
    overview: '가난한 김씨 가족이 부유한 박씨 가족의 집에 침투하면서 벌어지는 예측 불가능한 이야기. 계급과 빈부격차를 풍자하다.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8b8R8l889jeHVMPag0HPwcBnSpR.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/8b8R8l889jeHVMPag0HPwcBnSpR.jpg',
    rating: 9.1,
    genre: '드라마',
    releaseDate: new Date('2019-05-30'),
    runningTime: 132,
    director: '봉준호',
    cast: ['송강호', '이선균', '조여정', '박소담'],
    openDate: new Date('2019-05-30'),
    closeDate: null,
    status: 'now_playing',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

const MOCK_THEATERS: Theater[] = [
  {
    id: 't1',
    name: 'CGV 건대입구',
    location: '서울 광진구',
    address: '서울 광진구 자양로 36 (자양동)',
    phone: '1544-1191',
    thumbnailUrl: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 't2',
    name: 'CGV 용산아이파크몰',
    location: '서울 용산구',
    address: '서울 용산구 한강대로 245 (용산동 6가)',
    phone: '1544-1191',
    thumbnailUrl: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 't3',
    name: 'CGV 분당역',
    location: '경기 성남시',
    address: '경기 성남시 분당구 판교로 252 (야탑동)',
    phone: '1544-1191',
    thumbnailUrl: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 't4',
    name: 'CGV 동대문DTC',
    location: '서울 중구',
    address: '서울 중구 필동로 85 (필동)',
    phone: '1544-1191',
    thumbnailUrl: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    movieId: '1',
    userId: 'u1',
    username: '영화광',
    content: '압도적인 비주얼과 흥미진진한 스토리라인. CGV에서 대형 스크린으로 봐야 제맛!',
    rating: 4.5,
    createdAt: new Date('2025-04-25'),
    updatedAt: new Date(),
  },
  {
    id: 'r2',
    movieId: '1',
    userId: 'u2',
    username: '시네필',
    content: '액션 장면이 훌륭했지만 중간 전개가 조금 느렸음. 그래도 전작을 본 사람이라면 필수 관람.',
    rating: 3.5,
    createdAt: new Date('2025-04-26'),
    updatedAt: new Date(),
  },
  {
    id: 'r3',
    movieId: '6',
    userId: 'u3',
    username: '한국영화사랑',
    content: '여전히 봐도 숨이 막히는 영화. 봉준호 감독의 걸작을 다시 한번 느낄 수 있음.',
    rating: 5.0,
    createdAt: new Date('2025-04-20'),
    updatedAt: new Date(),
  },
]

export { MOCK_MOVIES, MOCK_THEATERS, MOCK_REVIEWS }
